#Puerto
server:
  port: 8899
 
 #Cambiar el username y password que correspondan
spring:
  ##DATASOURCE
  datasource:
    url: jdbc:mysql://localhost:3306/hibernate_example?useSSL=false
    username: root
    password: adminadmin
   
  ## Configurar propiedades Hibernate 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    #show-sql: true
      
## Configurar Hibernate Logging
logging:
  level:
    org:
      hibernate:
        SQL:  DEBUG 
